config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  get 'about', to: 'pages#about'
  get 'features', to: 'pages#features', as: :user_root

  resources :ai_images, only: [:index, :new, :create]
  resources :ai_stories, only: [:index, :new, :create]

  root "pages#home"
end

app/models/ai_image.rb
class AiImage < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ai_images
end

app/controllers/ai_images_controller.rb
class AiImagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @ai_images = current_user.ai_images
  end

  def new
    @ai_image = AiImage.new
  end

  # Create action is working as expected. Commented out to save money
  # def create
  #   client = OpenAI::Client.new
  #   prompt = image_request_params[:prompt]
  #   response = client.images.generate(
  #     parameters: {
  #       prompt: prompt,
  #       size: "256x256"
  #       }
  #     )
      # if the image generation is successful, save the prompt and image URL to ai_image object
  #   if response.success?
  #     puts response.dig("data", 0, "url")
  #     @img_url = response["data"].first["url"]
  #     @ai_image = AiImage.new(user: current_user, prompt: @prompt, img_url: @img_url)

  #     if @ai_image.save
  #       redirect_to ai_images_path, notice: 'AI Image was successfully created.'
  #     else
  #       render :new, notice: :unprocessable_entity
  #     end
  #   else
  #     error_message = response.body["message"]
  #     redirect_to new_ai_image_path, alert: "Failed to generate image: #{error_message}"
  #   end

  def create #create action for testing
    prompt = image_request_params[:prompt]
    @ai_image = AiImage.create!(user: current_user, prompt: prompt, img_url: "https://cdn.pixabay.com/photo/2014/06/03/19/38/board-361516__340.jpg")
      if @ai_image.save
        redirect_to ai_images_path, notice: 'AI Image was successfully created.'
      else
        render :new, notice: :unprocessable_entity
      end
  end

  private

  def image_request_params
    params.require(:ai_image).permit(:prompt)
  end
end

app/controllers/ai_stories_controller.rb
class AiStoriesController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def features
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/ai_images_helper.rb
module AiImagesHelper
end

app/helpers/ai_stories_helper.rb
module AiStoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ai_images/_ai_image.html.erb
<div class="mb-3 card card-body">
  <div class="me-4">
      <%= image_tag ai_image.img_url %>
      <%= ai_image.prompt %>
  </div>
</div>

app/views/ai_images/_image_request_form.html.erb
<%= simple_form_for @ai_image do |f| %>
  <div class="form-group">
    <%= f.text_area :prompt, class:'form-control' %>
  </div>
  <%= f.submit "Submit", class:'btn btn-outline-secondary' %>
<% end %>

app/views/ai_images/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Generated Images</h1>
  <%= link_to 'Create new image', new_ai_image_path, class:'btn btn-outline-secondary' %>
  <% if current_user.ai_images.any? %>
    <%= render @ai_images %>
  <% end %>

  <% if current_user.ai_images.none? %>
    <%= 'No images yet' %>
  <% end %>
</div>

app/views/ai_images/new.html.erb
<div class="container mt-5">
  <h1>Generate an image</h1>
  <%= render partial: 'image_request_form' %>
</div>

app/views/ai_stories/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Generated Stories</h1>
</div>

app/views/ai_stories/new.html.erb
<div class="container mt-5">
  <h1>Generate an story</h1>
  <%= render partial: 'story_request_form' %>
</div>

app/views/home/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>ClassroomGPT</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AI Explorer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= render partial: 'shared/navbar' %>
    <div class="container">
      <%= render partial: 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h2>About AI Explorer</h2>
  <p>
  AI Explorer is a web-based educational platform introducing young people
  to AI through interactive activities and games. It features a user-friendly
  interface, visually appealing design, and gamified approach to learning.
  Users learn about AI basics, applications, and real-world examples through
  challenges, quizzes, and mini-projects. The platform also offers resources
  for further learning and exploration. AI Explorer inspires future careers
  in AI and prepares young people for an AI-driven world.
  </p>
</div>
<div class="container">
  <h3>Exposure to emerging technology: </h3>
  <p>AI is rapidly becoming a major part
  of our daily lives and future careers, providing early exposure to AI
  helps young people understand its potential and start thinking about
  future opportunities.
  </p>
</div>
<div class="container">
  <h3>Develop critical thinking skills: </h3>
  <p>Learning about AI helps develop
  analytical and critical thinking skills that can be applied to other
  areas of life.
  </p>
</div>
<div class="container">
  <h3>Improve digital literacy: </h3>
  <p>AI is a crucial aspect of modern digital
  technology, and understanding it can help improve overall digital literacy
  and technology skills.
  </p>
</div>
<div class="container">
  <h3>Inspire future careers: </h3>
  <p>AI offers a wide range of career opportunities
  and learning about it can help young people discover their passions and
  inspire future careers.
  </p>
</div>
<div class="container">
  <h3>Prepare for the future: </h3>
  <p>With AI increasingly shaping the future, it
  is important for young people to be knowledgeable and prepared for an
  AI-driven world.
  </p>
</div>

app/views/pages/features.html.erb
<div class="container px-4 py-5" id="hanging-icons">
  <h2 class="pb-2 border-bottom">Try these AI activities</h2>
  <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
    <div class="col d-flex align-items-start">
      <div class="icon-square text-bg-light d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
        <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"/></svg>
      </div>
      <div>
        <h3 class="fs-2">Generate an image</h3>
        <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
        <%= link_to 'View Images', ai_images_path, class:'btn btn-primary' %>
        <%= link_to 'Create', new_ai_image_path, class:'btn btn-outline-secondary' %>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <div class="icon-square text-bg-light d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
        <svg class="bi" width="1em" height="1em"><use xlink:href="#cpu-fill"/></svg>
      </div>
      <div>
        <h3 class="fs-2">Write a story</h3>
        <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
        <%= link_to 'View Stories', ai_stories_path, class:'btn btn-primary' %>
        <%= link_to 'Create', new_ai_story_path, class:'btn btn-outline-secondary' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h3 class="display-4 fw-normal">Bringing AI to Classrooms Around the World</h3>
      <p class="lead fw-normal">Interactive Activities to Learn About AI</p>
      <%= link_to "Get Started", new_user_registration_path, class:"btn btn-outline-secondary" %>
    </div>
  </div>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="text-bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="text-bg-primary me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>
</main>

<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
      <small class="d-block mb-3 text-muted">&copy; 2023–</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Cool stuff</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Resource name</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Education</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Team</a></li>
        <li><a class="link-secondary" href="#">Locations</a></li>
        <li><a class="link-secondary" href="#">Privacy</a></li>
        <li><a class="link-secondary" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role='alert'>
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-info mt-4" role='alert'>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'AI Explorer', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Features', user_root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
      </ul>
        <ul class="navbar-nav">
          <%= render 'shared/usernav' %>
        </ul>
    </div>
  </div>
</nav>

app/views/shared/_usernav.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      User
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end">
      <li><a class="dropdown-item" href="#">Action</a></li>
      <li><a class="dropdown-item" href="#">Another action</a></li>
      <li><hr class="dropdown-divider"></li>
      <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
    </ul>
  </li>
<% else %>
  <li>
    <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
  </li>
  <li>
    <%= link_to "Log in", new_user_session_path, class:"nav-link" %>
  </li>
<% end %>